### PR TITLE
Added crude emoji support

### PR DESCRIPTION
**Pull request by NullableInt**
Currently supports a few emoji.
Why not all? I will investigate this.

### CODE REVIEW

**Comment by asbjornu** [comment]
@NullableInt, is this ready for review?

**Comment by NullableInt** [comment]
Almost. Not all emojies are supported, just a subset. I'll investigate why.
If you run it locally only 2 of 4 shown emojies are rendered.

**Comment by NullableInt** [comment]
It is now ready for review @asbjornu . It seems there are a few differences between the names of emojies. 🦄 is named :unicorn_face: on slack for instance. I do not know which is correct.

**Comment by asbjornu** [comment]
We shall see [here](https://swedbankpay.github.io/swedbank-pay-design-guide-jekyll-theme/) in a short while wether this works or not.

**Comment by asbjornu** [comment]
Works! 🎉

**Comment by NullableInt** [comment]
One could think I knew what I were doing.

**Comment by asbjornu** [comment]
What an absurd suggestion.

**Pull request merged**
