### PR TITLE
Upgrade jekyll-plantuml to version 2.0.1

### PR DESCRIPTION
**Pull request by asbjornu**
To fix URL, deployment and build problems. Hopefully.

### CODE REVIEW

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-design-guide-jekyll-theme/pullRequest?prid=5763147&bid=18864991)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-design-guide-jekyll-theme/pullRequest?prid=5763147&bid=18864991)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-design-guide-jekyll-theme/pullRequest?prid=5763147&bid=18864991)

**Comment by asbjornu** [comment]
Verify fails because of all the junk added from Developer Portal. I think we should merge this and see whether the URLs behave better after a new deploy.

**Comment by NullableInt** [comment]
> 
> 
> Verify fails because of all the junk added from Developer Portal. I think we should merge this and see whether the URLs behave better after a new deploy.

Go ahead. Merge and deploy on a Friday afternoon

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-design-guide-jekyll-theme/pullRequest?prid=5763147&bid=18864991)

**Pull request merged**
