### PR TITLE
Feature/dx 1631 new design in theme

### PR DESCRIPTION
**Pull request by trieutran91**
This PR is the MVP2 of https://www.figma.com/file/Ys5zmsVCmYt3yL4DruLzj0/FrontPage-V3-Entry?node-id=395%3A63894.
It is more detail-oriented than MVP1 and alignment is a big part of this PR.

### CODE REVIEW

**Comment by trieutran91** [comment]
I don't understand the "Unknown rule unit-whitelist" message from Codacy. What does it mean @asbjornu ?

**Comment by asbjornu** [comment]
> I don't understand the "Unknown rule unit-whitelist" message from Codacy. What does it mean @asbjornu ?

It seems like a bug. But since it's related to whitespace, just make sure the whitespace you use is consistent (no mixing of tabs and spaces, the same indent everywhere, etc.).

**Comment by trieutran91** [comment]
I have a theory about "Unknown rule unit whitelist".
I believe that the `unit whitelist` rule in Codacy is deprecated and should be replaced with `unit-allowed-list` instead.
Is that a rule you can change in the Codacy app?
image

**Comment by asbjornu** [comment]
Codacy is configured to read Stylelint configuration from the [`.stylelintrc` file](https://github.com/SwedbankPay/swedbank-pay-design-guide-jekyll-theme/blob/main/.stylelintrc). I suppose we copied that from Design Guide at one point and need to update it?

**Comment by asbjornu** [comment]
In the Design Guide, there's also a few [`stylelint` packages installed](https://github.com/SwedbankPay/design.swedbankpay.com/blob/f03bf11c48b0bdc7726eaf6740ed3a2275d19a2a/package.json#L95-L97) which may be a wise thing to do here in theme as well, just to have the same setup.

**Comment by trieutran91** [comment]
Aha. I can update `stylelint` in a different PR. Both the configuration and the packages. Then rebase this PR upon the changes.
How does that sound?

**Comment by asbjornu** [comment]
Sounds splendid, @trieutran91! 🙌🏼

**Review by asbjornu — APPROVED** [review]
👏🏼

**Pull request merged**
